console.log('module', this)

try {
  b = 4
  console.log(b)
} catch (err) {
  console.error(err)
}
